### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-menu-bar-flow#1]
child of https://github.com/vaadin/vaadin-core/issues/208

* Initialize the repo with skeleton base
* Branch protection
* Build setup (TC snapshot & release builds, release checklist)

**Comment by pekam** [comment]
- Project initialized
- PR validation build in teamcity.vaadin.com
- Branch protected by teamcity-build and CLA (not by review)
- Snapshot build in bender.vaadin.com
- Release build in bender.vaadin.com

**Comment by heruan** [comment]
A curiosity about naming: I guess this is the Flow integration of `vaadin-menu`, but this project and its modules are named as `vaadin-menu-bar-flow`; also, the stub component class is `MenuBar`. Is the `bar` part going to be removed or will this diverge from the common naming convention of Flow integrations?

**Comment by pekam** [comment]
@heruan, it was decided last week that the component will be called `vaadin-menu-bar` instead of `vaadin-menu` after all.
The renaming has not been done yet in the web component repository.
