### ISSUE TITLE
NoClassDefFoundError during init

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/vaadin-menu-bar-flow#18]
The current release (1.0.0-alpha1) produces a `NoClassDefFoundError `because `MenuItemsArrayGenerator `is missing.

```
java.lang.NoClassDefFoundError: com/vaadin/flow/component/contextmenu/MenuItemsArrayGenerator
	at deployment.product.war//com.vaadin.flow.component.menubar.MenuBar.<init>(MenuBar.java:57)
	at deployment.product.war//com.my.company.SomeClass.createMenuBar(SomeClass.java:99)
```

**Comment by pekam** [comment]
Hi!

As stated in the release notes, `MenuBar` requires version 2.1 of `vaadin-context-menu-flow`.
So you need to override the context-menu version as well to use menu-bar with existing platform versions. 

Both of these new versions will be included in Vaadin 14 to ensure compatibility.

**Comment by pekam** [comment]
I updated the release notes to highlight this more.

We'd be glad to hear any other feedback or problems you have with `MenuBar`!

**Comment by gsedlacz** [comment]
Thank you for your quick reply.
Ill give it try.
