### ISSUE TITLE
Menu items with subitems should has some icons

### ISSUE THREAD

**Issue by AlexeiBugai** [vaadin/vaadin-menu-bar-flow#27]
Hi Pekka!
MenuBar needs some enhancement, but I pretty sure that you have this in your plans.
Menu items with subitems should has some icons to indicate presents of subitems or opened status when user press on button.
Thank you.

**Comment by pekam** [comment]
Hi!

Actually, there are no plans for having this kind of icons by default. If you look at most menu bars in desktop applications, they don't have such icons either.

You could add the icon manually if you want:
```java
MenuItem item = menuBar.addItem("Foo");
item.add(new Icon(VaadinIcon.CHEVRON_DOWN));
```
(apply additional sizing/spacing to the icon if needed)
Do you mean an icon like this?

Unfortunately, changing the icon based on the opened-state is not that simple. It should be doable with some CSS tricks though. If you really need this and want some help, I can try to come up with a solution later.

**Comment by AlexeiBugai** [comment]
Hi Pekka!

Yes, something like this, but CHEVRON_RIGHT. And when menu opened - CHEVRON_DOWN (like hierarchy column in TreeGrid).
I will be very grateful if you can help. This will be very useful to many people, and you can add this solution to the examples for MenuBar.

Thank you.

**Comment by pekam** [comment]
Okay, here's one way to do it.
Let's add the `CHEVRON_RIGHT` icon by default:
```java
MenuItem item = menuBar.addItem("Foo");
item.add(new Icon(VaadinIcon.CHEVRON_RIGHT));
```
Then, let's create an HTML-file with a style module, with this kind of content:
```html
<dom-module id="menu-bar-styles" theme-for="vaadin-menu-bar">
    <template>
        <style>
            vaadin-menu-bar-button[expanded] iron-icon[icon="vaadin:chevron-right"] {
                transform: rotate(90deg);
            }

            vaadin-menu-bar-button iron-icon {
                /* If you want a smooth animation: */
                transition: 0.1s;
            }
        </style>
    </template>
</dom-module>
```
Import this HTML-file with the `@HtmlImport` annotation on your view-class.

So with this solution, we don't change the icon, but instead just rotate the `CHEVRON_RIGHT` icon 90 degrees when the button has attribute `expanded` (i.e. when the sub-menu is opened).

**Comment by AlexeiBugai** [comment]
Super! Thank you!
