### ISSUE TITLE
Vertical alignment of text

### ISSUE THREAD

**Issue by AlexeiBugai** [vaadin/vaadin-menu-bar-flow#30]
Hi Pekka!

Left - usual button, right - MenuBar.
It would be nice to have a same vertical alignment of text for buttons and for MenuBar by default.

[https://imgur.com/a/yP6Uri8](https://imgur.com/a/yP6Uri8)

Thank you very much!

**Comment by pekam** [comment]
We have just released 1.0.0.rc1 which should fix this issue. Are you still using alpha1?

**Comment by AlexeiBugai** [comment]
I have this issue with 1.0.0.rc1.

**Comment by pekam** [comment]
Ok. How are you creating those icons? It seems that with the normal button you are using the Vaadin `Icon` component, but with menu-bar they look like something else.

**Comment by AlexeiBugai** [comment]
Just played with different options (with VaadinIcon also) - button text is 1 pixel higher of MenuBar item text.
```
						menuItem = menuActions.addItem("Edit");
						menuItem.addComponentAsFirst(new Icon(VaadinIcon.USER));
```

**Comment by pekam** [comment]
> button text is 1 pixel higher of MenuBar item text

I don't understand. In my mind "button text" means the same as "MenuBar item text".

**Comment by AlexeiBugai** [comment]
Please check link with button and Menubar. 
[https://imgur.com/a/Sw4TV1L](https://imgur.com/a/Sw4TV1L)
You can try - put Menu Bar and Button in one line.

**Comment by pekam** [comment]
Well, I wouldn't consider 1 pixel difference a problem. :) I don't think anyone can notice that.

Btw, `vaadin-button-flow` version 2.0.0.rc1 has some fixes mostly related to the styling of icons, but might affect this case as well.

**Comment by AlexeiBugai** [comment]
Thank you!
