### ISSUE TITLE
TypeError: e.path is undefined

### ISSUE THREAD

**Issue by AlexeiBugai** [vaadin/vaadin-menu-bar-flow#44]
With beta2
TypeError: e.path is undefined
/frontend/menubarConnector.js:45

**Comment by pekam** [comment]
Hi!

Which browser are you using? Can you test if it works in Chrome?

Apparently `composedPath()` is the standard way instead of `path`

**Comment by AlexeiBugai** [comment]
Firefox. No error in chrome. But in chrome I get empty buttons again:
![image](https://user-images.githubusercontent.com/14044587/58321996-5a487380-7e28-11e9-9504-d2daea6bee33.png)

**Comment by pekam** [comment]
Ok, I made a fix for the TypeError issue. Sorry for the inconvenience.

But I can't reproduce the empty buttons issue in Chrome. Can you provide more info on that?

**Comment by AlexeiBugai** [comment]
Everything the same. Buttons with hidden subitems.
[24](https://github.com/vaadin/vaadin-menu-bar-flow/issues/24)

**Comment by pekam** [comment]
I still can't reproduce.
Here's my code:
```java
MenuBar menuBar = new MenuBar();
MenuItem foo = menuBar.addItem("foo");
MenuItem bar = menuBar.addItem("bar");
foo.getSubMenu().addItem("hide button", e -> foo.setVisible(false));
add(menuBar);
```

**Comment by AlexeiBugai** [comment]
Sorry, my buttons was with subitems, but you can reproduce with simple code:
```
MenuBar menuBarTest = new MenuBar();
MenuItem menuItemTest = menuBarTest.addItem("test");
menuItemTest.setVisible(false);
```

**Comment by pekam** [comment]
Ok, thanks! So it happens only when there are no visible items at all. If there is at least one visible item, the bug doesn't occur.

I know that this is caused by a web component issue: https://github.com/vaadin/vaadin-menu-bar/issues/74. We'll try to get it fixed for V14 stable.
