### ISSUE TITLE
Setting checked state doesn't have effect

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-menu-bar-flow#46]
I need to set some items of the `MenuBar` submenus as checked on certain events, but using `item.setChecked(true)` while the submenu is closed doesn't have any effect; it works instead while the submenu is opened (e.g. when clicking on the item).

Minimal example:

```java
var bar = new MenuBar();
var menu = bar.addItem("Parent").getSubMenu();
var item = menu.addItem("Child", e -> e.getSource().setChecked(true)); // <- working
item.setCheckable(true);

add(bar, new Button("Check", e -> item.setChecked(true)); // <- not working
```

**Comment by pekam** [comment]
It seems that the server and client get out of sync only when the checked state is changed programmatically after the initial rendering of the component, but before the overlay containing the checkable item is rendered for the first time.

Setting the checked state initially works.
Changing the state after the overlay has been opened (once or more) works.
