### ISSUE TITLE
1.0 SNAPSHOT build fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/vaadin-menu-bar-flow#68]
Menu Bar 1.0-SNAPSHOT build in bender fails due to test failures. See the build history [here](https://bender.vaadin.com/viewType.html?buildTypeId=Flow_ComponentSnapshot_MenuBar&tab=buildTypeHistoryList). It looks unstable in a way that every time new tests are failing. It should be investigated and fixed.

**Comment by mehdi-vaadin** [comment]
It works fine locally.

**Comment by web-padawan** [comment]
Looks like this is fixed. Closing.
